//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirstApproch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class arbajadonetdbEntities : DbContext
    {
        public arbajadonetdbEntities()
            : base("name=arbajadonetdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<trainer> trainers { get; set; }
    
        public virtual int uspInsertTrainer(string name, string city, Nullable<int> experience)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var experienceParameter = experience.HasValue ?
                new ObjectParameter("experience", experience) :
                new ObjectParameter("experience", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertTrainer", nameParameter, cityParameter, experienceParameter);
        }
    
        public virtual ObjectResult<uspGetTrainers_Result> uspGetTrainers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetTrainers_Result>("uspGetTrainers");
        }
    }
}
