//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirstApproch
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Rollnumber { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Trainerid { get; set; }
    
        public virtual trainer trainer { get; set; }
    }
}
